### PR TITLE
Remove cli container

### PR DESCRIPTION
**Pull request by sbani**
cli containers are useless because fpm container is the same
installation routine and could be used for cli process too.

### CODE REVIEW

**Review by eFzvai — APPROVED** [review]

**Comment by razbakov** [comment]
Please integrate [this change](https://github.com/banovo/docker-php/commit/8f926fc15fffa4f22fa4c37e2a97b8ef1886c7f6) to fpm docker

**Comment by sbani** [comment]
Rebased the branch which removes the merge problems.

I think about a new directory structure. Instead of the current one, I would propose the following:
```bash
$ tree .
.
├── Dockerfile.5
├── Dockerfile.5.dev
├── Dockerfile.7
├── Dockerfile.7.dev
├── LICENSE
├── README.md
└── docker-entrypoint.sh
```

With this directory structure, we have only one `docker-entrypoint.sh` which prevents code duplication. This structure is very common when dealing with multiple `DockerFile`s but only one entrypoint script.

**Comment by razbakov** [comment]
@sbani I like the idea, but alas `Dockerfile Location` configuration in hub.docker.com allow to define only the directory, not the file name.

**Comment by sbani** [comment]
@razbakov: You are right. I thought it's possible but it seems like the others build the images without docker hub.

I would leave it like it is now in this this PR.

**Review by razbakov — CHANGES_REQUESTED** [review]
Please integrate changes I mentioned before

**Comment by sbani** [comment]
See #35

**Review by razbakov — APPROVED** [review]

**Comment by sbani** [comment]
Test are failing because of the f***g 
> /usr/bin/env: php: Text file busy

Errors. We have to ignore it. I haven't found a way to fix it.

**Pull request merged**
